media:
  input: blog/assets
  output: assets
  
components:
  seo:
    type: object
    label: SEO
    fields:
      - name: title
        label: Titel
        type: string
      - name: description
        label: Beschreibung
        type: text
        
content:
  - name: Posts
    type: collection
    path: blog
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: seo
        label: SEO information
        component: seo
      - name: pubDate
        label: Published Date
        type: date
        options:
          format: MMM dd yyyy
      - name: heroImage
        label: Hero Image
        type: image
      - name: body
        label: Body
        type: rich-text
    view:
      fields: [title, description, pubDate, heroImage]
      
  - name: PageInfo
    label: Seiten-Informationen
    description: Informationen und Einstellungen für die gesamte Seite
    type: file
    path: src/_data/pageinfo.json
    fields:
      - name: title
        label: Seitenname
        type: string
        
settings:
  commit: 
    identiy: user