name: Build Astro
description: Install dependencies and build the Astro application

runs:
  using: composite
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build Astro app
      shell: bash
      run: pnpm build
